version: '3.8'
services:
  app:
    restart: always
    build: .
    working_dir: /app
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: whattoeat
      MYSQL_USER: whattoeat
      MYSQL_PASSWORD: 123change
    ports:
      - "3306:3306"