CREATE TABLE IF NOT EXISTS product (
    id int not null AUTO_INCREMENT PRIMARY KEY,
    name varchar(100),
    unit varchar(10),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;